"""
build.py — Assemble the static demo into demo/site/.

The site folder is self-contained and can be served by any static host
(Hugging Face Static Space, GitHub Pages, or a local server):

    python demo/build.py
    python -m http.server -d demo/site 8000

The online experiment (docs/chirp-demo) is included under experiment/.
Publish to Hugging Face with demo/publish_hf.py.
"""

import json
import shutil
from pathlib import Path

DEMO = Path(__file__).resolve().parent
REPO = DEMO.parent
SITE = DEMO / "site"

# Files loaded into Pyodide by worker.js: {path in site: source path}
PYTHON_FILES = {
    f: REPO / f
    for f in [
        "src/__init__.py",
        "src/program/__init__.py",
        "src/program/type.py",
        "src/program/helpers.py",
        "src/program/primitive.py",
        "src/program/router.py",
        "src/program/grammar.py",
        "src/domain/__init__.py",
        "src/domain/melody/__init__.py",
        "src/domain/melody/melody_utils.py",
        "src/domain/melody/melody_primitive.py",
        "src/domain/melody/base_compressor.py",
        "src/domain/melody/greedy_dp_compressor.py",
    ]
}
PYTHON_FILES["inference.py"] = DEMO / "inference.py"
PYTHON_FILES["data/task_pm.csv"] = REPO / "data" / "primitive" / "task_pm.csv"

# recorder.json is generated by recorder.py
PAGE_FILES = ["index.html", "style.css", "app.js", "worker.js", "recorder.json"]
EXPERIMENT = REPO / "docs" / "chirp-demo"

HF_README = """---
title: Melody Program Induction
emoji: 🎵
colorFrom: indigo
colorTo: blue
sdk: static
pinned: false
---

In-browser demo for *Harmonizing Program Induction with Rate-Distortion Theory*
(CogSci 2024). Code: https://github.com/zhouhq10/program-induction-rdt (built from `demo/`).

- [Model demo](https://zhouhq10-program-induction-rdt.static.hf.space/index.html):
  compress melodies into programs, sweep β and watch the library grow.
- [Experiment](https://zhouhq10-program-induction-rdt.static.hf.space/experiment/index.html):
  the online melody-learning task participants completed (preview mode, no data is saved).
"""


def main() -> None:
    if SITE.exists():
        shutil.rmtree(SITE)

    copies = dict(PYTHON_FILES)
    copies.update({f: DEMO / f for f in PAGE_FILES})
    for dst, src in copies.items():
        (SITE / dst).parent.mkdir(parents=True, exist_ok=True)
        shutil.copy(src, SITE / dst)

    shutil.copytree(EXPERIMENT, SITE / "experiment",
                    ignore=shutil.ignore_patterns(".DS_Store"))

    (SITE / "files.json").write_text(json.dumps(list(PYTHON_FILES), indent=1))
    (SITE / "README.md").write_text(HF_README)
    print(f"Built {len(copies)} files into {SITE}")


if __name__ == "__main__":
    main()
